# Generated by Django 2.0.2 on 2018-02-18 20:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ana_Bilim_Dali',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adi', models.CharField(max_length=100)),
                ('ing_adi', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Birim',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birim_turu', models.CharField(choices=[('A', 'Akademik'), ('I', 'İdari')], max_length=1, verbose_name='Birim Türü')),
                ('birim_kategori', models.CharField(choices=[('F', 'Fakülte'), ('M', 'MYO'), ('Y', 'Yüksekokul'), ('E', 'Enstitü'), ('K', 'Koordinatörlük'), ('R', 'Rektörlüğe Bağlı Birim')], max_length=1, verbose_name='Birim Kategori')),
                ('adi', models.CharField(max_length=200)),
                ('ing_adi', models.CharField(max_length=200)),
                ('birim_kodu', models.CharField(max_length=2)),
                ('birim_kodu2', models.CharField(max_length=10)),
                ('genel_bilgi', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Bolum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adi', models.CharField(max_length=200)),
                ('ing_adi', models.CharField(max_length=200)),
                ('alt_birim_kodu', models.CharField(max_length=2)),
                ('alt_birim_kodu2', models.CharField(max_length=10)),
                ('genel_bilgi', models.TextField()),
                ('birim', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='pbs.Birim', verbose_name='Fakülte/MYO')),
            ],
        ),
        migrations.CreateModel(
            name='Personel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adi_soyadi', models.CharField(max_length=50)),
                ('sicil', models.CharField(max_length=5)),
                ('telefon', models.CharField(max_length=7)),
                ('e_posta', models.CharField(max_length=30)),
                ('genel_bilgi', models.TextField()),
                ('ana_bilim_dali', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='pbs.Ana_Bilim_Dali', verbose_name='Ana Bilim Dalı')),
                ('birim', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='pbs.Birim', verbose_name='Birimi')),
                ('bolum', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='pbs.Bolum', verbose_name='Bölümü')),
            ],
        ),
        migrations.AddField(
            model_name='ana_bilim_dali',
            name='bolum',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pbs.Bolum'),
        ),
        migrations.AddField(
            model_name='ana_bilim_dali',
            name='fakulte',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pbs.Birim'),
        ),
    ]
