# Generated by Django 2.0.2 on 2018-02-25 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pbs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaksi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deskripsi', models.TextField()),
                ('jumlah', models.DecimalField(decimal_places=2, max_digits=20)),
                ('dibuat', models.DateField(auto_now_add=True)),
                ('diubah', models.DateField(auto_now=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='birim',
            options={'verbose_name': 'Birim', 'verbose_name_plural': 'Birimler'},
        ),
    ]
