# Generated by Django 2.0.2 on 2018-02-25 12:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pbs', '0002_auto_20180225_0919'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaksi',
            name='pemilik',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
