# Generated by Django 2.0.2 on 2018-02-25 12:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pbs', '0003_transaksi_pemilik'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaksi',
            name='pemilik',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
